def rename_note(note):
    try:
        note = {
            " great": "mood: great",
            " happy": "mood: happy",
            " ok": "mood: ok",
            " sad": "mood: sad",
            " weird": "mood: weird",
            "Abi morgen": "Abi morgen",
            "Alcohol": "Alcohol",
            "Anstrengender Tag": "Anstrengender Tag",
            "Anxious": "Anxious",
            "Ate Vegan": "Ate Vegan",
            "Ate Vegetarian": "Ate Vegetarian",
            "Ate late": "Ate late",
            "Ate nothing": "Ate nothing",
            "Bad Day": "Bad Day",
            "Bath": "Bath",
            "Blaze": "Smoked Marihuana",
            "Bright Screen before Sleep": "Bright Screen before Sleep",
            "Broken bones": "Broken bones",
            "Coffee": "Drank Coffee",
            "Cold Shower": "Cold Shower",
            "Daylight": "Daylight",
            "Drank Alcohol": "Drank Alcohol",
            "Drank Soda": "Drank Soda",
            "E": "E",
            "Essen bestellt": "Essen bestellt",
            "Fapped": "Fapped",
            "Feeling Under Pressure": "Feeling Under Pressure",
            "Feeling stupid": "Feeling stupid",
            "Gelenkschmerzen": "Gelenkschmerzen",
            "Good day": "Good day",
            "Had Sex": "Had Sex",
            "Headache": "Headache",
            "Heuschnupfen": "Heuschnupfen",
            "Heute etwas gelernt": "Heute etwas gelernt",
            "Husten": "Husten",
            "In Augsburg": "In Augsburg",
            "In Bed with Selina": "In Bed with Selina",
            "In Berlin ": "In Berlin ",
            "In Heidelberg": "In Heidelberg",
            "In Ulm": "In Ulm",
            "In bed with Steffi": "In bed with Steffi",
            "In the Hospital": "In the Hospital",
            "Kaffee getrunken": "Kaffee getrunken",
            "Knieschmerzen": "Knieschmerzen",
            "Kopfschmerzen": "Kopfschmerzen",
            "Listening to Music": "Listening to Music",
            "Meditation right before sleep": "meditated right before sleep",
            "Meditation": "meditated",
            "Nap": "Nap",
            "On Reddit/YT before sleep": "On Reddit or YT before sleep",
            "On Vacation": "On Vacation",
            "Sad Day": "Sad Day",
            "Schnupfen": "Schnupfen",
            "Shower": "Shower",
            "Sick": "sick",
            "Sleeping in a tent ": "Sleeping in a tent ",
            "Sleeping under clean sky": "Sleeping under clean sky",
            "Smoked Cigarettes": "Smoked Cigarettes",
            "Smoked Tabacco": "Smoked Tabacco",
            "Smoked Weed": "Smoked Marihuana",
            "Sport gemacht": "Sport gemacht",
            "Spät gegessen": "Spät gegessen",
            "StaVo-Dinge gemacht": "StaVo-Dinge gemacht",
            "Stayed Inside All Day": "Stayed Inside All Day",
            "Stressful day": "Stressful day",
            "Tea": "Drank Tea",
            "Tee getrunken": "Tee getrunken",
            "Thai-Massage": "Thai-Massage",
            "Tired": "Tired",
            "Worked out": "Worked out",
            "Writing Exam tomorrow": "Writing Exam tomorrow",
            "Zahnschmerzen": "Zahnschmerzen",
            "Zahnspange": "Zahnspange",
            "ambitious": "ambitious",
            "anki": "anki",
            "at least one pull-up": "at least one pull-up",
            "ate healthy food": "ate healthy food",
            "ate unhealthy food": "ate unhealthy food",
            "auf dem Pfadi-Lager": "auf dem Pfadi-Lager",
            "big bike tour": "big bike tour",
            "cleaned up my room": "cleaned up my room",
            "code milestone": "code milestone",
            "cooked for myself": "cooked for myself",
            "did mental exercises / brain jogging": "did mental exercises or brain jogging",
            "did some physics": "did some physics",
            "dinner was great": "dinner was great",
            "drank enough": "drank enough",
            "drunk": "drunk",
            "durcheinander ": "durcheinander ",
            "f this s": "f this s",
            "feeling weak": "feeling weak",
            "gemütlich": "gemütlich",
            "gereizt drauf": "gereizt drauf",
            "gruppenstunde": "gruppenstunde",
            "heart broken": "heart broken",
            "honest": "honest",
            "hot": "hot",
            "hungry": "hungry",
            "hurtful skin": "hurtful skin",
            "in love": "in love",
            "kaputte/rissige Hände": "kaputte oder rissige Hände",
            "kiefer-physioth. uebungen": "kiefer-physioth. uebungen",
            "leichte Rückenschmerzen": "leichte Rückenschmerzen",
            "life is great": "life is great",
            "little bit of beer": "little bit of beer",
            "lonely": "lonely",
            "lots of gaming": "lots of gaming",
            "meditated": "meditated",
            "met Selina": "met Selina",
            "mood": None,
            "no dinner": "no dinner",
            "orged": "orged",
            "played guitar ": "played guitar ",
            "played piano": "played piano",
            "played video games": "played video games",
            "puked": "puked",
            "rachen kratzt": "rachen kratzt",
            "read a few pages before sleep": "read a few pages before sleep",
            "sick": "sick",
            "small bike tour": "small bike tour",
            "stoned": "stoned",
            "stressed": "stressed",
            "table tennis": "table tennis",
            "tischkicker": "tischkicker",
            "took a walk": "took a walk",
            "war am Haus": "war am Haus",
            "wrote code": "wrote code",
        }[note]
    except KeyError:
        return None
    return note
